before:
  hooks:
    - go mod tidy
    - go generate .
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    flags:
      - -tags=vfs
    ldflags: -s -w -X main.VERSION={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    goarm:
      - "6"
brews:
  - tap:
      owner: codeskyblue
      name: homebrew-tap
    folder: Formula
