sudo: required
services:
  - docker
language: go
go:
  - "1.10"
script:
  - go test -v
addons:
  apt:
    packages:
      - docker-ce
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    script:
    - bash docker/push_images
    - bash docker/push_manifest
    on:
      branch: master
